### ISSUE TITLE
Documentation request

### ISSUE THREAD

**Issue by eggsyntax** [clojure-emacs/sayid#38]
Hi,

I'm definitely appreciating Sayid now that I'm spending more time with it! Unfortunately, a lot of the documentation shows only key chords. For example, from the overview: "Press `C-c s w` to get an overview of what has been captured in the Sayid workspace". For those of us using different bindings (eg evil-mode users, spacemacs users) that doesn't really tell us anything. It would be really helpful if when you give a key chord, you could also include the name of the function. A lot of emacs packages do it parenthetically, which IMHO works well, ie  "Press `C-c s w` (`sayid-workspace-overview`) to get an overview of what has been captured in the Sayid workspace".

Thanks much! With or without this change, Sayid is awesome :)

**Comment by bpiel** [comment]
@eggsyntax Glad you like it! And, thanks for the suggestion. Makes sense.

My time for sayid has suffered as I've been focused on guildsman this past year. Guildsman is starting to feel stalled though, so maybe I'll return to sayid and try to knock out some of these issues, including this one. You are welcome and encouraged to submit a PR for this :smile: but otherwise I hope to get to it sometime.

thanks
